// This file is part of CycloneDX MSBuild Task for .NET
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Patrick Dwyer. All Rights Reserved.

using System.Security.Cryptography;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;

namespace CycloneDX.MSBuildTask;

/// <summary>
/// MSBuild task that generates a CycloneDX SBOM from resolved references and NuGet package data.
/// </summary>
public class GenerateSbomTask : Microsoft.Build.Utilities.Task
{
    [Required]
    public string OutputDirectory { get; set; } = "";

    [Required]
    public string ProjectName { get; set; } = "";

    public string? ProjectVersion { get; set; }

    public string? TargetFramework { get; set; }

    public string? RuntimeIdentifier { get; set; }

    /// <summary>
    /// Resolved assembly references from MSBuild's ResolveAssemblyReferences target.
    /// Expected metadata: NuGetPackageId, NuGetPackageVersion, HintPath, ResolvedFrom, FusionName.
    /// </summary>
    public ITaskItem[]? ResolvedReferences { get; set; }

    /// <summary>
    /// Runtime pack assets for self-contained builds (e.g. Microsoft.NETCore.App.Runtime.linux-x64).
    /// Expected metadata: NuGetPackageId, NuGetPackageVersion.
    /// </summary>
    public ITaskItem[]? RuntimePackAssets { get; set; }

    /// <summary>
    /// Satellite (resource) assemblies from MSBuild's ResolveAssemblyReferences target.
    /// Expected metadata: NuGetPackageId, NuGetPackageVersion, CultureName.
    /// </summary>
    public ITaskItem[]? SatelliteReferences { get; set; }

    /// <summary>
    /// Declared PackageReference items from the project file.
    /// </summary>
    public ITaskItem[]? PackageReferences { get; set; }

    /// <summary>
    /// Path to the project.assets.json file generated by NuGet restore.
    /// </summary>
    public string? ProjectAssetsFile { get; set; }

    public override bool Execute()
    {
        try
        {
            var input = BuildInput();
            var generator = new SbomGenerator();
            var bom = generator.Generate(input);

            Directory.CreateDirectory(OutputDirectory);
            WriteBom(bom);

            Log.LogMessage(MessageImportance.Normal,
                "CycloneDX SBOM generated: {0}/bom.json, {0}/bom.xml ({1} components)",
                OutputDirectory, bom.Components?.Count ?? 0);

            return true;
        }
        catch (Exception ex)
        {
            Log.LogErrorFromException(ex, showStackTrace: true);
            return false;
        }
    }

    internal SbomInput BuildInput()
    {
        var resolvedRefs = (ResolvedReferences ?? [])
            .Select(item =>
            {
                var hintPath = NullIfEmpty(item.GetMetadata("HintPath"));
                return new ResolvedReferenceInfo
                {
                    FileName = Path.GetFileNameWithoutExtension(item.ItemSpec),
                    Version = item.GetMetadata("Version"),
                    NuGetPackageId = NullIfEmpty(item.GetMetadata("NuGetPackageId")),
                    NuGetPackageVersion = NullIfEmpty(item.GetMetadata("NuGetPackageVersion")),
                    HintPath = hintPath,
                    ResolvedFrom = NullIfEmpty(item.GetMetadata("ResolvedFrom")),
                    FusionName = NullIfEmpty(item.GetMetadata("FusionName")),
                    FileHashHex = ComputeFileHashHex(hintPath ?? item.ItemSpec),
                };
            })
            .ToList();

        // Add runtime pack assets (self-contained builds) as additional resolved references
        foreach (var item in RuntimePackAssets ?? [])
        {
            resolvedRefs.Add(new ResolvedReferenceInfo
            {
                FileName = Path.GetFileNameWithoutExtension(item.ItemSpec),
                NuGetPackageId = NullIfEmpty(item.GetMetadata("NuGetPackageId")),
                NuGetPackageVersion = NullIfEmpty(item.GetMetadata("NuGetPackageVersion")),
                HintPath = item.ItemSpec,
                FileHashHex = ComputeFileHashHex(item.ItemSpec),
            });
        }

        // Add satellite (resource) assemblies as additional resolved references
        foreach (var item in SatelliteReferences ?? [])
        {
            resolvedRefs.Add(new ResolvedReferenceInfo
            {
                FileName = Path.GetFileNameWithoutExtension(item.ItemSpec),
                NuGetPackageId = NullIfEmpty(item.GetMetadata("NuGetPackageId")),
                NuGetPackageVersion = NullIfEmpty(item.GetMetadata("NuGetPackageVersion")),
                HintPath = item.ItemSpec,
                FileHashHex = ComputeFileHashHex(item.ItemSpec),
                CultureName = NullIfEmpty(item.GetMetadata("CultureName")),
            });
        }

        var packageRefs = (PackageReferences ?? [])
            .Select(item => new PackageReferenceInfo
            {
                Name = item.ItemSpec,
                Version = NullIfEmpty(item.GetMetadata("Version")),
            })
            .ToList();

        ProjectAssetsData? assets = null;
        if (!string.IsNullOrEmpty(ProjectAssetsFile) && File.Exists(ProjectAssetsFile))
        {
            Log.LogMessage(MessageImportance.Low,
                "Reading NuGet assets from: {0}", ProjectAssetsFile);
            assets = ProjectAssetsReader.Read(ProjectAssetsFile, TargetFramework, RuntimeIdentifier);
        }

        return new SbomInput
        {
            ProjectName = ProjectName,
            ProjectVersion = ProjectVersion,
            TargetFramework = TargetFramework,
            ResolvedReferences = resolvedRefs,
            PackageReferences = packageRefs,
            ProjectAssets = assets,
        };
    }

    private void WriteBom(CycloneDX.Models.Bom bom)
    {
        var jsonPath = Path.Combine(OutputDirectory, "bom.json");
        var json = CycloneDX.Json.Serializer.Serialize(bom);
        File.WriteAllText(jsonPath, json);

        var xmlPath = Path.Combine(OutputDirectory, "bom.xml");
        var xml = CycloneDX.Xml.Serializer.Serialize(bom);
        File.WriteAllText(xmlPath, xml);
    }

    internal static string? ComputeFileHashHex(string? filePath)
    {
        if (string.IsNullOrEmpty(filePath) || !File.Exists(filePath))
            return null;

        using var stream = File.OpenRead(filePath);
        var hashBytes = SHA256.HashData(stream);
        return Convert.ToHexString(hashBytes).ToLowerInvariant();
    }

    private static string? NullIfEmpty(string? value) =>
        string.IsNullOrEmpty(value) ? null : value;
}
