# For details of what checks are run for PRs please refer below
name: .NET Core CI

on: [pull_request, workflow_dispatch]

env:
  SNAPSHOOTER_STRICT_MODE: true

# see https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions: {}

jobs:
  # Fail if there are build warnings
  #
  # As a general code quality check we use FxCop analyzers.
  #
  # To check for build warnings locally you may need to run a clean build.
  #
  # This can be done by running `dotnet clean` before running `dotnet build`
  build-warnings:
    name: Build warnings check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build /WarnAsError

  test:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#       os: [ubuntu-latest, windows-latest, macos-latest] 
#       macos currently disabled. see issue #285 for more info.
        os: [ubuntu-latest, windows-latest]
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'

    - name: Tests
      run: |
        dotnet test test/CycloneDX.MSBuildTask.Tests

  integration-tests:
    name: Integration Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Tests
      run: |
        dotnet test test/CycloneDX.MSBuildTask.IntegrationTests
